# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Vivado/pipeline_cpu/pipeline_cpu.cache/wt [current_project]
set_property parent.project_path E:/Vivado/pipeline_cpu/pipeline_cpu.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Vivado/pipeline_cpu/pipeline_cpu.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Vivado/prgmip32.COE
read_verilog -library xil_defaultlib {
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/ALU.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/DM_unit.v
  E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/EX_MEM_Reg.v
  E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/ID_EX_Reg.v
  E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/IF_ID_Reg.v
  E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/sources_1/new/MEM_WB_Reg.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/RegFile.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/aluctr.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/ctr.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/display.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/next_pc.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/signext.v
  E:/Vivado/single_cpu/single_cpu.srcs/sources_1/new/Top.v
}
read_ip -quiet E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/IM_unit/IM_unit.xci
set_property used_in_implementation false [get_files -all e:/Vivado/pipeline_cpu/pipeline_cpu.srcs/sources_1/ip/IM_unit/IM_unit_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/constrs_1/new/pipline_cpu.xdc
set_property used_in_implementation false [get_files E:/Vivado/pipeline_cpu/pipeline_cpu.srcs/constrs_1/new/pipline_cpu.xdc]


synth_design -top top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
