# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DirectoryServer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x44irectoryServer.proto\"\x1c\n\tDir_Reply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1a\n\tDir_Empty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\"N\n\rFileServer_On\x12\x11\n\tServer_ID\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"#\n\x0e\x46ileServer_Off\x12\x11\n\tServer_ID\x18\x01 \x01(\x05\"P\n\x0f\x46ileServer_info\x12\x11\n\tServer_ID\x18\x01 \x01(\x05\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\"8\n\x0f\x46ileServer_List\x12%\n\x0bserver_list\x18\x01 \x03(\x0b\x32\x10.FileServer_info2\xa4\x01\n\tDirServer\x12\x31\n\x11\x66ileserver_online\x12\x0e.FileServer_On\x1a\n.Dir_Reply\"\x00\x12\x33\n\x12\x66ileserver_offline\x12\x0f.FileServer_Off\x1a\n.Dir_Reply\"\x00\x12/\n\rgetfileserver\x12\n.Dir_Empty\x1a\x10.FileServer_List\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'DirectoryServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIR_REPLY']._serialized_start=25
  _globals['_DIR_REPLY']._serialized_end=53
  _globals['_DIR_EMPTY']._serialized_start=55
  _globals['_DIR_EMPTY']._serialized_end=81
  _globals['_FILESERVER_ON']._serialized_start=83
  _globals['_FILESERVER_ON']._serialized_end=161
  _globals['_FILESERVER_OFF']._serialized_start=163
  _globals['_FILESERVER_OFF']._serialized_end=198
  _globals['_FILESERVER_INFO']._serialized_start=200
  _globals['_FILESERVER_INFO']._serialized_end=280
  _globals['_FILESERVER_LIST']._serialized_start=282
  _globals['_FILESERVER_LIST']._serialized_end=338
  _globals['_DIRSERVER']._serialized_start=341
  _globals['_DIRSERVER']._serialized_end=505
# @@protoc_insertion_point(module_scope)
