# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileServer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x46ileServer.proto\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x16\n\x05\x45mpty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\"5\n\x0eUpload_Request\x12\x13\n\x0btarget_path\x18\x01 \x01(\t\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\x0c\")\n\x10\x44ownload_Request\x12\x15\n\rdownload_path\x18\x01 \x01(\t\"%\n\x0e\x44\x65lete_Request\x12\x13\n\x0b\x64\x65lete_path\x18\x01 \x01(\t\" \n\x0cList_Request\x12\x10\n\x08\x63ur_path\x18\x01 \x01(\t\"!\n\rMkdir_Request\x12\x10\n\x08\x64ir_path\x18\x01 \x01(\t\"\x18\n\x05Reply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1a\n\nList_Reply\x12\x0c\n\x04list\x18\x01 \x01(\t\"\x18\n\tPWD_Reply\x12\x0b\n\x03pwd\x18\x01 \x01(\t2\xcd\x02\n\nFileServer\x12%\n\x06upload\x12\x0f.Upload_Request\x1a\x06.Reply\"\x00(\x01\x12\x31\n\x12upload_without_syn\x12\x0f.Upload_Request\x1a\x06.Reply\"\x00(\x01\x12)\n\x08\x64ownload\x12\x11.Download_Request\x1a\x06.Chunk\"\x00\x30\x01\x12#\n\x06\x64\x65lete\x12\x0f.Delete_Request\x1a\x06.Reply\"\x00\x12/\n\x12\x64\x65lete_without_syn\x12\x0f.Delete_Request\x1a\x06.Reply\"\x00\x12$\n\x04list\x12\r.List_Request\x1a\x0b.List_Reply\"\x00\x12\x1b\n\x03pwd\x12\x06.Empty\x1a\n.PWD_Reply\"\x00\x12!\n\x05mkdir\x12\x0e.Mkdir_Request\x1a\x06.Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'FileServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CHUNK']._serialized_start=20
  _globals['_CHUNK']._serialized_end=43
  _globals['_EMPTY']._serialized_start=45
  _globals['_EMPTY']._serialized_end=67
  _globals['_UPLOAD_REQUEST']._serialized_start=69
  _globals['_UPLOAD_REQUEST']._serialized_end=122
  _globals['_DOWNLOAD_REQUEST']._serialized_start=124
  _globals['_DOWNLOAD_REQUEST']._serialized_end=165
  _globals['_DELETE_REQUEST']._serialized_start=167
  _globals['_DELETE_REQUEST']._serialized_end=204
  _globals['_LIST_REQUEST']._serialized_start=206
  _globals['_LIST_REQUEST']._serialized_end=238
  _globals['_MKDIR_REQUEST']._serialized_start=240
  _globals['_MKDIR_REQUEST']._serialized_end=273
  _globals['_REPLY']._serialized_start=275
  _globals['_REPLY']._serialized_end=299
  _globals['_LIST_REPLY']._serialized_start=301
  _globals['_LIST_REPLY']._serialized_end=327
  _globals['_PWD_REPLY']._serialized_start=329
  _globals['_PWD_REPLY']._serialized_end=353
  _globals['_FILESERVER']._serialized_start=356
  _globals['_FILESERVER']._serialized_end=689
# @@protoc_insertion_point(module_scope)
