# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LockServer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10LockServer.proto\"\x1d\n\nLock_Reply\x12\x0f\n\x07success\x18\x01 \x01(\x05\"\x1b\n\nLock_Empty\x12\r\n\x05\x65mpty\x18\x01 \x01(\x05\"Y\n\x0clockfileinfo\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x11\n\tlock_type\x18\x04 \x01(\x05\"H\n\x0eunlockfileinfo\x12\x11\n\tclient_id\x18\x01 \x01(\x05\x12\x11\n\tfile_path\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t2d\n\nLockServer\x12(\n\x08lockfile\x12\r.lockfileinfo\x1a\x0b.Lock_Reply\"\x00\x12,\n\nunlockfile\x12\x0f.unlockfileinfo\x1a\x0b.Lock_Reply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'LockServer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOCK_REPLY']._serialized_start=20
  _globals['_LOCK_REPLY']._serialized_end=49
  _globals['_LOCK_EMPTY']._serialized_start=51
  _globals['_LOCK_EMPTY']._serialized_end=78
  _globals['_LOCKFILEINFO']._serialized_start=80
  _globals['_LOCKFILEINFO']._serialized_end=169
  _globals['_UNLOCKFILEINFO']._serialized_start=171
  _globals['_UNLOCKFILEINFO']._serialized_end=243
  _globals['_LOCKSERVER']._serialized_start=245
  _globals['_LOCKSERVER']._serialized_end=345
# @@protoc_insertion_point(module_scope)
