# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import LockServer_pb2 as LockServer__pb2


class LockServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.lockfile = channel.unary_unary(
                '/LockServer/lockfile',
                request_serializer=LockServer__pb2.lockfileinfo.SerializeToString,
                response_deserializer=LockServer__pb2.Lock_Reply.FromString,
                )
        self.unlockfile = channel.unary_unary(
                '/LockServer/unlockfile',
                request_serializer=LockServer__pb2.unlockfileinfo.SerializeToString,
                response_deserializer=LockServer__pb2.Lock_Reply.FromString,
                )


class LockServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def lockfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unlockfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LockServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'lockfile': grpc.unary_unary_rpc_method_handler(
                    servicer.lockfile,
                    request_deserializer=LockServer__pb2.lockfileinfo.FromString,
                    response_serializer=LockServer__pb2.Lock_Reply.SerializeToString,
            ),
            'unlockfile': grpc.unary_unary_rpc_method_handler(
                    servicer.unlockfile,
                    request_deserializer=LockServer__pb2.unlockfileinfo.FromString,
                    response_serializer=LockServer__pb2.Lock_Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'LockServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LockServer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def lockfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LockServer/lockfile',
            LockServer__pb2.lockfileinfo.SerializeToString,
            LockServer__pb2.Lock_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def unlockfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/LockServer/unlockfile',
            LockServer__pb2.unlockfileinfo.SerializeToString,
            LockServer__pb2.Lock_Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
